version: "3.10"
services:
  face-recog:
    image: "facerecogref"
    container_name: main
    restart: "always"
    build: .
    ports:
      - "3345:3345"
    volumes:
      - .:/code
    environment:
      - LOG_LEVEL=debug
